//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiraeusBankImport.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class ErgoSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ErgoSettings defaultInstance = ((ErgoSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ErgoSettings())));
        
        public static ErgoSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38.03.00.0006")]
        public string ErgopartnersAcc {
            get {
                return ((string)(this["ErgopartnersAcc"]));
            }
            set {
                this["ErgopartnersAcc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38.03.00.0003")]
        public string ErgoplanningAcc {
            get {
                return ((string)(this["ErgoplanningAcc"]));
            }
            set {
                this["ErgoplanningAcc"] = value;
            }
        }
    }
}
